version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000 #python manage.py makemigrations && python manage.py migrate && 
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7.5
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/db/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: hello_django
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: hello_django_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    
volumes:
  mysql_data: